### PR TITLE
Introduce style.scss. Add npm task 'build-css'. Update README and travis config file.

### PR DESCRIPTION
**Pull request by BassT**
Introduce style.scss. Add npm task 'build-css'. Update README and travis config file.

### CODE REVIEW

**Comment by jGleitz** [comment]
Add this point we're introducing generated files.

I think we should build into a separate directory (like `build`) and exclude this directory from the repository.

**Comment by BassT** [comment]
Agreed. I'll fix it.

**Comment by vzickner** [comment]
Can you additional add your name to the list of the contributors?
To automate the installation and build process, this should maybe done in the script `postinstall` or a separate command `npm build`? At the current solution we need for everything another command, this is not really handy.

**Comment by BassT** [comment]
I added `postinstall` commands for deployment and development to the npm scripts. I created two seperate ones since I thought running test could take a long time on a local machine, so it shouldn't be done in the development postinstall by default and I wasn't sure if browsertest script can be run locally.

**Comment by jGleitz** [comment]
browsertest can be run locally, but I still think it's a good idea to keep it separate.

**Comment by jGleitz** [comment]
looks good to me.

At a later point we'll have to unify watching files with tools like [npm watch](https://www.npmjs.com/package/watch).

**Pull request merged**
